name: planejacampo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.2
  firebase_crashlytics: ^4.3.2
  provider: ^6.1.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  shared_preferences: ^2.5.2
  path: ^1.9.0
  font_awesome_flutter: ^10.8.0
  mask_text_input_formatter: ^2.9.0
  intl: ^0.19.0
  dropdown_search: ^6.0.2
  connectivity_plus: ^6.1.3
  validators: ^3.0.0
  flutter_multi_formatter: ^2.13.0
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  tutorial_coach_mark: ^1.2.12
  showcaseview: ^4.0.1
  fl_chart: ^0.70.2
  ionicons: ^0.2.2
  line_awesome_flutter: ^3.0.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geodesy: ^0.10.2
  flutter_polyline_points: ^2.1.0


  flutter_background_service: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  nested: any
  tuple: ^2.0.2

  file_picker: ^9.0.0
  archive: ^4.0.2
  xml: ^6.5.0
  flutter_speed_dial: ^7.0.0

  uuid: ^4.5.1

  mockito: ^5.4.5
  build_runner: ^2.4.15

  mutex: ^3.1.0

  rxdart: ^0.28.0
  date_kit: ^1.0.2


flutter_intl:
  enabled: true
  generate: true
  output_dir: lib/l10n
  arb_dir: lib/l10n
  template_arb_file: intl_pt_BR.arb
  main_locale: pt_BR


dev_dependencies:
  intl_utils: ^2.8.10
  flutter_test:
    sdk: flutter
  flutter_dotenv: ^5.1.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/logo.png
    - assets/plant_logo.png
    - assets/plant_logo2.png
    - assets/logo2.png
    - assets/logo3.png
    - assets/google_icon.png
    - assets/android_neutral_rd_na@4x.png
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
